# Generated by Django 5.2.16 on 2026-07-19 13:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0003_alter_machine_options_alter_site_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('operational', 'Operational'), ('warning', 'Warning'), ('critical', 'Critical'), ('maintenance', 'Under Maintenance'), ('offline', 'Offline')], default='operational', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipments', to='machinery.machine')),
            ],
            options={
                'db_table': 'equipments',
                'ordering': ['name'],
            },
        ),
    ]
