# Generated by Django 5.2.16 on 2026-07-19 15:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('machinery', '0004_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentTelemetry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('sensor_readings', models.JSONField()),
                ('health_score', models.FloatField(default=100.0)),
                ('failure_probability', models.FloatField(default=0.0)),
                ('status', models.CharField(default='operational', max_length=50)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='machinery.equipment')),
            ],
            options={
                'db_table': 'equipment_telemetry',
                'ordering': ['-timestamp'],
            },
        ),
    ]
